### ISSUE TITLE
Format Date

### ISSUE THREAD

**Issue by rottanak** [RenovoSolutions/ngx-datetimepicker#43]
Could you tell me how to format show in input like "DD-MMM-YYYY"?

**Comment by alecrem** [comment]
The Date service is putting the date strings together on its own instead of using the locale, so this is going to take some work.

For reference, this is from the PR where I made it possible to have the time in a 24 hour format: https://github.com/RenovoSolutions/ngx-datetimepicker/pull/66/commits/4afd978f87e98829bb7fc2d93ada811b9c719ffd

Feel free to ping me if you are going to take on this issue.

**Comment by ghost** [comment]
Any chance of still getting this to work? I had a look at the source and see that it returns a different format for mobile, so it should be possible?

**Comment by benjamin-a-kuntz** [comment]
Format added in https://github.com/RenovoSolutions/ngx-datetimepicker/pull/160
